# Generated by Django 4.2.6 on 2023-11-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_category_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(max_length=300)),
                ('y', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Yetkazib beruvchi kardinatasi',
                'verbose_name_plural': 'Yetkazib beruvchi kardinatasi',
            },
        ),
    ]
