# Generated by Django 4.2.6 on 2023-11-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_cordinate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cordinate',
            options={'verbose_name': 'Yetkazib beruvchi manzili', 'verbose_name_plural': 'Yetkazib beruvchi manzili'},
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
    ]
