# Generated by Django 4.2.6 on 2023-11-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_cordinate_options_order_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.BooleanField(default=False, verbose_name='Yetkazib berish ximati bormi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Buyurtma topshirildimi'),
        ),
    ]
